### ISSUE TITLE
Transient dependencies and upgrade from 3.5.1 to 3.6.0

### ISSUE THREAD

**Issue by dbrattli** [thoth-org/Thoth.Json.Net#28] opened 2019-11-05 20:11 UTC
Projects that upgrades from 3.5.1 to 3.6.0 and depends on NuGet's built with 3.5.1 breaks with runtime error: "Method not found: 'Microsoft.FSharp.Core.FSharpResult`2<Int32,System.Tuple`2<System.String,Thoth.Json.Net.ErrorReason>> Thoth.Json.Net.Decode.int(System.String, Newtonsoft.Json.Linq.JToken)'." 

Just a heads up. I have no idea what the problem is. Recompiling dependencies with 3.6.0 seems to fix the problem.

**Comment by MangelMaxime** [comment] 2019-11-06 09:13
It looks similar to an error reported by @forki about Thoth.Json.Giraffe 2.2.0 not being compatible with version Thoth.Json 3.6.0 at runtime.

I suspect it's because we changed the implementation of `Decode.int`

- [Before](https://github.com/thoth-org/Thoth.Json.Net/blob/07661f9eb4a7b7a4d753095cec3e4465701a4a40/src/Decode.fs#L140-L154)
- [Now](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Decode.fs#L206-L212)

For me, it wasn't a breaking change because the API didn't change, but it seems like .Net can't do the link by itself...

I am not sure about what should be done in such a case, because I think this is a "problem" caused by how .Net runtime work. I don't believe JavaScript runtime would break in such a situation.

Even if I bump Thoth.Json.Net to a major version, the problem will stay the same (from what I suspect).

Perhaps, we should add a note on the documentation explaining that if the user sees this error, it needs to recompile its library against Thoth.Json.Net 3.6.0?

@forki @dbrattli @isaacabraham How do people manage such case when working on .Net libraries?

**Comment by isaacabraham** [comment] 2019-11-19 10:50
@MangelMaxime looking at the before and after, it looks like it *is* a breaking change because of the removal of the `fun path token` bit? I could be wrong here.

**Comment by MangelMaxime** [comment] 2019-11-19 12:22
Well, the underlying implementation is different but the exposed API is exactly the same.

The type of `int` is still `Decoder<int>` which still ask for [`fun path value ->`](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Decode.fs#L156) (ok it's called `value` not `token` but still expect a `Newtonsoft.Json.Linq.JToken` type).

**Comment by MangelMaxime** [comment] 2020-07-01 21:45
I am closing as not much can be done now.

I suppose next time, I change an underlying API I will need to think about making a major version.

**Closed by MangelMaxime** 2020-07-01 21:45 UTC
